#!/bin/bash

# cryptez-<VERSION>
# Month DD, YYYY

# License: GPLv3
# Copyright 2011-<CURRENT YEAR> Jamie Carranza (jamie@demurgatroid.net)

# Makes maintaining encrypted files simple.  Encrypted files are kept in
# SECRETS_DIR for easy access.

# Cryptez only writes decrypted files to the directory specified as "TMP_DIR",
# this directory should be located in memory, e.g. tmpfs

# Default location of encrypted files
SECRETS_DIR=~/.cryptez

# Decrypted files directory
TMP_DIR="/tmp/cryptez.${RANDOM}"

# Use anything valid for use with the `openssl` command
CIPHER='aes-256-cbc'

# Read/write editor command
EDITOR_RW='/usr/bin/vim'

# Read only editor command
EDITOR_RO='/usr/bin/vi -R'

# Whether to open for editing by default (0 = no, 1 = yes)
EDIT='0'

#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

PATH='/bin:/usr/bin'
PWD=`pwd`
MV=0

umask 077

USAGE () {
cat <<EOF
Usage: cryptez [ OPTIONS ] [ FILE ]

View, create, and edit encrypted files

OPTIONS
    -e      edit
    -c      cipher
    -h      display usage

EOF
exit 0
}

TRAP () {
    echo -e "caught signal\nWARNING: decrypted files may exist!"
    #kill -- "-$$"
    exit
}

# Trap signals
trap 'TRAP; exit 1' 2 15

# PROCESS OPTIONS
while
    getopts ":ec:h" options; do
        case $options in
            e ) EDIT=1 ;;
            c ) CIPHER="$OPTARG" ;;
            h ) USAGE && exit 0 ;;
            * ) USAGE && exit 1 ;;
        esac
done
shift $(($OPTIND - 1))

NAME="$1"

mkdir "$TMP_DIR"

# Error out if input file doesn't exist and "-e" option not given
if ! [ -e "${SECRETS_DIR}/${NAME}.cryptez" ] && [ $EDIT -eq 0 ]; then
    echo "${SECRETS_DIR}/${NAME}.cryptez does not exist, use '-e' to open new file"
    exit 1
fi

if [ -d "$SECRETS_DIR" ] || mkdir -p "$SECRETS_DIR"; then :
else
    echo "Cannot create $SECRETS_DIR"
    exit 1
fi

# if input file is "data", try to decrypt
if
    file "${SECRETS_DIR}/${NAME}.cryptez" | grep "data" &>/dev/null
then
        if
        
        openssl $CIPHER -d -salt -in "${SECRETS_DIR}/${NAME}.cryptez" \
        -out "${TMP_DIR}/${NAME}.cryptez.txt"
    then :
    else
        echo 'decryption failed ...exiting'
        exit 0
    fi
fi

if
    [ $EDIT -eq 0 ]
then
    $EDITOR_RO ${TMP_DIR}/${NAME}.cryptez.txt
    rm -Rf "$TMP_DIR"
    exit 0
fi

[ $EDIT -eq 1 ] && $EDITOR_RW ${TMP_DIR}/${NAME}.cryptez.txt

# Encrypt file
openssl $CIPHER -salt -in ${TMP_DIR}/${NAME}.cryptez.txt -out "${SECRETS_DIR}/${NAME}.cryptez"

rm -Rf "$TMP_DIR"

